version: '3'
services:
  postgres:
    container_name: mikro-orm-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mikro-orm-data

volumes:
  db_data: ~
